version: 2

sources:
  - name: staging
    database: true-vista-335505
    schema: tripdata_all
      # loaded_at_field: record_loaded_at
    tables:
      - name: green_tripdata
      - name: yellow_tripdata
      - name: fhv_tripdata
         # freshness:
           # error_after: {count: 6, period: hour}